### ISSUE TITLE
Move Website Files Up a Directory

### ISSUE THREAD

**Issue by loganfranken** [Samantha996/Promise-Scholar-Website#2]
Move the website files up a directory

**Comment by Samantha996** [comment]
Moved the files(html, CSS, js) up to Promise-Scholar-Website and deleted promise folder

**Comment by loganfranken** [comment]
![900x900px-ll-500be9b5_tumblr_m9j0sglarb1qz9mk5o1_400](https://cloud.githubusercontent.com/assets/1024444/15031650/2b08848a-120f-11e6-9532-2352308c9ca4.gif)
